# Generated by Django 3.2.8 on 2021-10-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Update Time')),
                ('id', models.UUIDField(default=None, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(db_index=True, default='', max_length=32, verbose_name='Firstname')),
                ('last_name', models.CharField(db_index=True, default='', max_length=56, verbose_name='Lastname')),
                ('patronymic', models.CharField(blank=True, default='', max_length=56, verbose_name='Patronymic')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
